### ISSUE TITLE
Notification under Bootstrap4 NavBar

### ISSUE THREAD

**Issue by TomEvin** [mckenziearts/laravel-notify#10]
Maybe it is just for me, but whatever I use, the notification it is always show up under the NavBar (top-right, top-left, center-top).

If I modify the CSS like this, it solve this:
`.notify-alert {
...
top: auto;
...
}`
`.connectify-alert {
...
top: auto;
...
}
`

**Comment by mckenziearts** [comment]
Hi Tom you can update the notify css to get your custom style or load your custom css file with your custom update to erase notify alert style
