### ISSUE TITLE
Not working with Laravel 10

### ISSUE THREAD

**Issue by eshe-huli** [mckenziearts/laravel-notify#108]
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/11230064/224525026-79046541-2e06-4369-bb30-33b51236ba45.png">

This is a fresh Laravel installation but the [package seams to not be supported

**Comment by philharmonie** [comment]
Highly demanded!

**Comment by jonesheckler** [comment]
any suggestions on how to resolve?

**Comment by iphyman** [comment]
The dev master branch already have support for illuminate/support 10, to use with Laravel 10 run `composer require mckenziearts/laravel-notify:dev-master`

**Comment by mcpuishor** [comment]
Tried the `dev-master` branch and it's still not compatible with L10. 
I found that `"mckenziearts/laravel-notify": "dev-l10-compatibility"` works in composer. 
It would be nice to have a stable version released, tho'.

**Comment by iphyman** [comment]
> Tried the `dev-master` branch and it's still not compatible with L10. I found that `"mckenziearts/laravel-notify": "dev-l10-compatibility"` works in composer. It would be nice to have a stable version released, tho'.

Not sure about your requirements but I was able to use the package in a fresh laravel 10 project and it works pretty well

**Comment by mckenziearts** [comment]
New release is available and compatible with laravel 10
