### ISSUE TITLE
Hardcoded success-warning-...

### ISSUE THREAD

**Issue by TomEvin** [mckenziearts/laravel-notify#11]
Could you please implement that the messages like this
`<i class="flaticon-like"></i><span>{{ session()->get('notify.type') }}</span>`
cannot be hardcoded, but read from the session like the title
`<h4>{{ session()->get('notify.title') }}</h4>` ?

Thanks!

**Comment by mckenziearts** [comment]
can you show an example of how you would please? Or you can make a pull request
