### ISSUE TITLE
Publishing not complete.

### ISSUE THREAD

**Issue by thakor-maheshkumar** [mckenziearts/laravel-notify#16]
Enter the command php artisan vendor:publish --provider='Mckenziearts\Notify\LaravelNotifyServiceProvider' 
than error Unable to locate publishable resources.
![Screenshot_1](https://user-images.githubusercontent.com/53993063/72216171-a9701f80-3543-11ea-92db-ab4f1e1c2d29.png)

**Comment by mckenziearts** [comment]
Try the solution of this issue #4

**Comment by thakor-maheshkumar** [comment]
thanks sir
