### ISSUE TITLE
position config setting not working

### ISSUE THREAD

**Issue by Chrisx84** [mckenziearts/laravel-notify#18]
i set my notify.php config to have `'position' => 'bottom-right',` but the notify still comes up in the top right, no matter where i set position to it always shows up in the top right corner of the browser.

**Comment by ghost** [comment]
Such a nice plugin ! I've got the same issue. I cannot figure out how to change the position / animation of the notification. Is there any way to do this ? I tried only with css but z-index is not enough. Thank you for your help if you can help us with that :)

**Comment by honorezemagho** [comment]
I've got the same issue, how to fix it?

**Comment by visualight** [comment]
Override CSS working.
Bottom - right

```
.inset-0 {
    top: auto!important;
}
```

**Comment by AbdullahKaram-Dev** [comment]
visualight where can i find this class

**Comment by visualight** [comment]
@AbdallaDev2 

1. Launches a notification
2. Inspect the code of the notification (right click: inspect element): need developper tools in your browser

**Comment by ghost** [comment]
Thank you !!

**Comment by larasylvio** [comment]
para poder poner el mensaje en la parte superior derecha (top-right) se tubo que instalar la libreria seguir tanto los pasos de Option 1: With Tailwind CSS & Alpinejs y Option 2: Without Tailwind CSS

y luego en las cabeceras del layout, poner en la seccion de head el siguiente estilo

        <style>
            .notify .fixed {
                left: auto !important;
                width: 400px; /* Ancho fijo */  
                max-width: 90%; /* Máximo 90% del ancho del contenedor */
                right: 10px !important; /* Espacio desde el borde derecho */
            }
            .notify .justify-center {
                justify-content: flex-end !important;
            }  
            .notify .items-center {
                align-items: flex-start !important;
            }                      
        </style>
        
        @notifyCss
