### ISSUE TITLE
Close button don't work

### ISSUE THREAD

**Issue by salioudiabate** [mckenziearts/laravel-notify#2]
Close button don't work and icons don't display automatically, it show only when I copied a fonts folder on my public folder

**Comment by vadimsg** [comment]
Same, wrong links to assets. Timeout also doesn't work. Message doesn't disappear.

**Comment by mckenziearts** [comment]
I fixed it thanks. I just published a new release. I will close the issue

**Comment by salioudiabate** [comment]
I done update but it same : Close button don't work
<img width="567" alt="Capture d’écran 2019-11-14 à 17 22 20" src="https://user-images.githubusercontent.com/12444680/68880536-588aa900-0703-11ea-8fe9-58811d630fc3.png">

**Comment by mckenziearts** [comment]
I have just done a test as presented on the gif and the button works correctly.

![notify](https://user-images.githubusercontent.com/14105989/68881076-c1c2ea00-070c-11ea-99c8-20eb15dbd375.gif)

**Comment by salioudiabate** [comment]
Ok I will try again later but say me what software are you used to record screen in gif on mac

**Comment by mckenziearts** [comment]
I don't record in gif, i record with quicktime and after i make a search on google how to transform my mov file to gif
