### ISSUE TITLE
Unable to prepare route [notify/demo] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by kajal098** [mckenziearts/laravel-notify#21]
When i upload my code on live server using deployer or when i clear my cache files it gives me error like this.
![Screenshot from 2020-02-29 16-50-48](https://user-images.githubusercontent.com/21876329/75606552-f7e97580-5b13-11ea-86a8-c6fea964d690.png)

**Comment by rutul8997** [comment]
I have the same issue. can you please solve as soon as possible.

**Comment by KrishnaChavda** [comment]
I have the same issue. can you please solve as soon as possible.
