### ISSUE TITLE
How to display notification in Javascript?

### ISSUE THREAD

**Issue by lovecoding-git** [mckenziearts/laravel-notify#28]
Hello,

Thanks for such great package.
I am using it for my Laravel Package.
Btw, is there any way to create notification in javascript?

**Comment by mckenziearts** [comment]
Hi, no this package it's provide to work only with laravel session, for javascript notifications you can use library such as sweet alert.

**Comment by lovecoding-git** [comment]
Thank you!
I love the style.
hmm, I would like to keep same style for both controller and javascript.
if I can open this in javascript, it will be great. :)

Thanks
