### ISSUE TITLE
Unable to close the flash notification

### ISSUE THREAD

**Issue by gausoft** [mckenziearts/laravel-notify#3]
First of all, congratulations guys for your work. 
When I integrate laravel-notify in my project, I can't close the fash notitication. Do you know why?

**Comment by mckenziearts** [comment]
Hi i already fix that issue here #2 with an example

**Comment by prasanthjanga** [comment]
I am also facing the same issue
not able to close and after time out it is not closing.

after taking the new version
"laravel/framework": "5.5.*",
"mckenziearts/laravel-notify": "^1.0"
![image](https://user-images.githubusercontent.com/8664873/68915026-77d51500-079b-11ea-83fa-46dfdd0b5ad9.png)

**Comment by mckenziearts** [comment]
I think i know what is the issue, in the readme i told to load javascript before include the messages, i think that is the problem. On your default layout update like this :

```blade
@include('notify::messages')
@notifyJs
```

in place of 

```blade
@notifyJs
@include('notify::messages')
```

**Comment by prasanthjanga** [comment]
> I think i know what is the issue, in the readme i told to load javascript before include the messages, i think that is the problem. On your default layout update like this :
> 
> ```
> @include('notify::messages')
> @notifyJs
> ```
> 
> in place of
> 
> ```
> @notifyJs
> @include('notify::messages')
> ```

Now it is working TQ

**Comment by mckenziearts** [comment]
You are welcome. i close the issue
