### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ahmednet0001** [mckenziearts/laravel-notify#34]
Hi
I use Bootstrsp RTL , 'top-let' position not wok  also close button not on the it place
![Untitled](https://user-images.githubusercontent.com/11617821/90675272-85538a00-e25a-11ea-9737-723755b51bff.png)

**Comment by mckenziearts** [comment]
This feature will not be implemented at the moment, you can do a PR if needed

**Comment by AHMED-GAMAL-AG** [comment]
@mckenziearts Hey, any updates?
