### ISSUE TITLE
Close button not working..

### ISSUE THREAD

**Issue by MHassanSaqib** [mckenziearts/laravel-notify#35]
I am getting the following error while closing the notification. Please guide me about it.

```
app.js:38298 [Vue warn]: Property or method "show" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
```

**Comment by mckenziearts** [comment]
Do you use vuejs on your project?

**Comment by MHassanSaqib** [comment]
Yes, I am using VueJS and including it using laravel scaffolding

**Comment by mckenziearts** [comment]
The package uses alpinejs and it doesn't work very well with frontend applications (React or Vuejs). It is based on a Laravel session to display the notification
