### ISSUE TITLE
notify.js not working

### ISSUE THREAD

**Issue by chapdel** [mckenziearts/laravel-notify#36]
Hello, when integrating notify on a laravel and VueJS project, the notify.js file could not be inserted. Here is the error I have in my console.

![SharedScreenshot](https://user-images.githubusercontent.com/20987014/91693683-b17cde00-eb6b-11ea-8f64-8bd31c4b7113.jpg)
have Possible solutions?

**Comment by mckenziearts** [comment]
Laravel Notify is not built to work with a frontend app like react or vuejs only work with laravel session
