### ISSUE TITLE
Question about self-closing 

### ISSUE THREAD

**Issue by Kacimi-Amine** [mckenziearts/laravel-notify#37]
hi ,
thank you for this awesome package,
please i wanted to know if there is a timer to add to have the self-closing of the alert  ...

**Comment by mckenziearts** [comment]
I plan to add it to the next release

**Comment by labomatik** [comment]
it can be handled with something like this in the blade notification file:
`x-init="setTimeout(() => { show = true }, 500);setTimeout(() => { show = false }, 5500)"`

**Comment by omaisali** [comment]
> it can be handled with something like this in the blade notification file:
> `x-init="setTimeout(() => { show = true }, 500);setTimeout(() => { show = false }, 5500)"`

didn't work for me
i need to replace with `<x:notify-messages />` ?

**Comment by omaisali** [comment]
> I plan to add it to the next release

Waiting ... :)

**Comment by kriiv** [comment]
> I plan to add it to the next release

This would be great!

**Comment by titusfrezer** [comment]
I think this come after upgrading so downgrading to the lowest version might help_

**Comment by mckenziearts** [comment]
New version released last saturday. More detail here https://github.com/mckenziearts/laravel-notify/releases/tag/v2.2
