### ISSUE TITLE
I'm getting an error while installing

### ISSUE THREAD

**Issue by antijen14** [mckenziearts/laravel-notify#40]
Hi, i use laravel 8. 

I just tried to install it with composer. But i take an error.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v8.1.0
    - Conclusion: don't install laravel/framework v8.1.0
    - mckenziearts/laravel-notify 2.x-dev requires illuminate/support ~7.0 -> satisfiable by illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0
, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3,
 v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - mckenziearts/laravel-notify v2.0 requires illuminate/support ~7.0 -> satisfiable by illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v
7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7
.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.3|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.4|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.5|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.6|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.7|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.0.8|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.1.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.1.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.1.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.1.3|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.10.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.10.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.10.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.10.3|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.11.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.12.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.13.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.14.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.14.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.15.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.16.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.16.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.17.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.17.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.17.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.18.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.19.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.19.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.2.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.2.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.2.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.20.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.21.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.22.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.22.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.22.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.22.3|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.22.4|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.23.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.23.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.23.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.24.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.25.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.26.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.26.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.27.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.28.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.28.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.3.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.4.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.5.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.5.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.5.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.6.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.6.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.6.2|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.7.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.7.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.8.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.8.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.9.0|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.9.1|don't install laravel/framework v8.1.0
    - don't install illuminate/support v7.9.2|don't install laravel/framework v8.1.0
    - Installation request for laravel/framework (locked at v8.1.0, required as ^8.0) -> satisfiable by laravel/framework[v8.1.0].
    - Installation request for mckenziearts/laravel-notify ^2.0 -> satisfiable by mckenziearts/laravel-notify[2.x-dev, v2.0].

Installation failed, reverting ./composer.json to its original content.
`

How can i solve this error? Thanks.

**Comment by CodeLover254** [comment]
**composer require mckenziearts/laravel-notify dev-master**

That will work until a new build is released.
