### ISSUE TITLE
Notification displayed twice

### ISSUE THREAD

**Issue by labomatik** [mckenziearts/laravel-notify#43]
The notification window is displayed twice (during the load of the page and then when the page is fully loaded)
Do you have any idea how to prevent that?

**Comment by labomatik** [comment]
`[x-cloak] { display: none; }`
did the trick

**Comment by sebreunion** [comment]
Hi @labomatik ,

Got the same exact issue... 

Any fix on your side ?

Thx

**Comment by gautamsolankidev** [comment]
I am having the same issue

**Comment by kgp43** [comment]
Same
