### ISSUE TITLE
The box remains under the content, not being read. How to solve this?

### ISSUE THREAD

**Issue by Marcolino92** [mckenziearts/laravel-notify#51]
The box remains under the content, not being read. How to solve this?

**Comment by kriiv** [comment]
If I'm understanding your question correctly, I fixed this by adding this to my css:

````
.inset-0 {
    z-index: 999 !important;
}
````

It's hacky but works, just hooks into a class and makes the box show up above all else. Hoping thats the issue you were having.

**Comment by ArdaGezekk** [comment]
I did what he said partially worked. Before I did it, the bottom of notify was under the content. How do I get the Notif on top of the Navbar?

![image](https://user-images.githubusercontent.com/55910759/109279422-c7bddb00-782a-11eb-9fbd-b47136164969.png)

**Comment by ArdaGezekk** [comment]
thank you @kriiv, I solved the problem.
