### ISSUE TITLE
Notify fired twice

### ISSUE THREAD

**Issue by Spillo17** [mckenziearts/laravel-notify#54]
Hi,

I'm using laravel 8 notify works very good, the only thing is that it fire one time very fast and diapered and after it comes "it suppose" the good one and sty there.

Can you help me ?

I put  @notifyCss in my head / @notifyJs in my footer and  <x:notify-messages /> in my blade page.

**Comment by Spillo17** [comment]
If I removed @notifyJs it goes correctly, but I cannot close with "x" and it doesn't disappear

**Comment by mckenziearts** [comment]
Do you have the same problem? Because a new release is available you can update the dependency and the problem will be solved
