### ISSUE TITLE
It's does not support in java script code 

### ISSUE THREAD

**Issue by gautampatel5317** [mckenziearts/laravel-notify#57]
- It's does not support in java script code 
- if i want specially in jquery or javascript code like toastr your notify message does not worked .
- for e.g toastr.success("User has been created successfully!")  this work in jquery and javascript but notify.success("Message") this is not worked . How we can use in jquery or javascript ?

**Comment by mckenziearts** [comment]
This package is not made to be used in javascript. It only works with Laravel session

**Comment by patricktan98** [comment]
@mckenziearts  Is it possible to allow us to manually call laravel-notify from pure javascript function?

**Comment by adam-torok** [comment]
.
