### ISSUE TITLE
Higher z-index value in css

### ISSUE THREAD

**Issue by MarkLester10** [mckenziearts/laravel-notify#62]
I think you should add higher z-index value, for the container, sometimes the message show at the back of navbar that has higher z-index value

**Comment by haexperts2020** [comment]
Same issue for me, this would be nice to override or update in the config file

**Comment by sovathchhinh** [comment]
In master blade
include stylesheet.
<style type="text/css">
          .notify{
              z-index: 1000000;
              margin-top: 5%;
          }
      </style>
this is work for me.

**Comment by EhtuCom** [comment]
> In master blade include stylesheet.
> 
> <style type="text/css"> .notify{ z-index: 1000000; margin-top: 5%; } </style>
> this is work for me.

Great this answer: It fixes the Z-Index problem plus top margin problems with the menu! 🥇

**Comment by Muhammad-Sarfaraz** [comment]
In my case I have used the class selector to change the position a little bit,

`.max-w-sm.w-full.bg-white.shadow-lg.rounded-lg.pointer-events-auto.border-l-4.border-green-600 {
            margin-top: 3% !important;
        }`
Also you can set your nav bar z-index to 0 to fix this problem.

`style:z-index:0!important ` in nav div.
