### ISSUE TITLE
[2.2] Urgent !. message.blade.php missing. 

### ISSUE THREAD

**Issue by magic-thomas** [mckenziearts/laravel-notify#65]
hi. 

I just finished upgrading laravel version with composer.

One of my project is using laravel-notify.

It got error after upgrading to laravel 8.45.1. 

Following file was missing. 

'vendor/mckenziearts/laravel-notify/resources/views/messages.blade.php' 

please fix it.

**Comment by karthikw3cert** [comment]
I face the same issue. I copy Messages.blade.php file from old backup its working fine now

**Comment by magic-thomas** [comment]
> I face the same issue. I copy Messages.blade.php file from old backup its working fine now

Yes. That is the first aid. 

But we should be able to update project again without throwing error.

**Comment by amrography** [comment]
replace 

```blade
@include('notify::message')
```

with 

```blade
@include('notify::components.notify')
```
