### ISSUE TITLE
unexpected 'Session' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by karthikw3cert** [mckenziearts/laravel-notify#66]
syntax error, unexpected 'Session' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) After Updating the Package
![🧨_syntax_error_unexpected_Session_T_STRING_expecting_function_T_FUNCTION_or_const_T_CONST_](https://user-images.githubusercontent.com/17139738/121332839-dd689380-c935-11eb-81ba-38bda74488b2.png)

**Comment by henkiws** [comment]
did you resolved this issue ? I have same issue 
only appear in my hosting

**Comment by henkiws** [comment]
![image](https://user-images.githubusercontent.com/25384498/209827708-14d59797-1b86-435d-b641-5f9eee0782b9.png)
