### ISSUE TITLE
Responsive (viewport)

### ISSUE THREAD

**Issue by rick195s** [mckenziearts/laravel-notify#7]
The Notification isn´t responsive in mobile view due to the meta name="viewport" content="width=device-width, initial-scale=1.0"
![Sem Título](https://user-images.githubusercontent.com/51890743/68993789-cce45a00-0873-11ea-9516-d6c7f4a465cf.png)

**Comment by youssef3wi** [comment]
Not yet even notification stay open

**Comment by mckenziearts** [comment]
This issue is fixed on v2. 👍🏾
