### ISSUE TITLE
Show notify many time at same time

### ISSUE THREAD

**Issue by codemenco** [mckenziearts/laravel-notify#77]
Hi,
Is there any way to show notify many time without replace the old one?
For example I have two alert want to show users one for error and other for success.

**Comment by lukebouch** [comment]
@codemenco Looking at the code it does not appear to support multiple notifications at a time, but I could be wrong. As an alternative, you could use [laracasts/flash](https://github.com/laracasts/flash) which is what I have been using and it does support multiple flash messages at a time.

**Comment by JoJo-Bear** [comment]
@codemenco you could take a look at my PR #92 it has however a few changes instead of one, not sure if it will be accepted but it should fix your issue.
