### ISSUE TITLE
Does not publish the configuration file and assets

### ISSUE THREAD

**Issue by takielias** [mckenziearts/laravel-notify#8]
It does not publish the required files by
 
`php artisan vendor:publish --provider='Mckenziearts\Notify\LaravelNotifyServiceProvider'` 

I got this Only [http://prntscr.com/pye0v7](http://prntscr.com/pye0v7) 

**Laravel 6.0**

**Comment by mckenziearts** [comment]
<img width="795" alt="Screenshot 2019-11-18 at 08 50 32" src="https://user-images.githubusercontent.com/14105989/69034035-94ae5a00-09e0-11ea-8328-0df54f85832a.png">

I just executed the same command and here is the result I just installed the package
