### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by isuru9732** [mckenziearts/laravel-notify#80]

**Comment by isuru9732** [comment]
this work for me https://github.com/mckenziearts/laravel-notify/issues/53#issuecomment-841777850

**Comment by supgeek-rod** [comment]
I had the same problem, them I solved it, look at the code below

``` blade
@include('notify::components.notify')

@notifyCss
@notifyJs
```

`@notifyJs` should come after `@include('notify::components.notify')`

🤣
