### ISSUE TITLE
Laravel 9.0.2 installation error

### ISSUE THREAD

**Issue by martijnschuman** [mckenziearts/laravel-notify#85]
I'm trying to install Notify v2 on Laravel 9.0.2 but I'm getting the following error:
`Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - mckenziearts/laravel-notify[v1.0, ..., 1.x-dev] require illuminate/support ~5.0|~6.0|~7.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires mckenziearts/laravel-notify 1.* -> satisfiable by mckenziearts/laravel-notify[v1.0, ..., 1.x-dev].`
    
I already ran `composer update`, `composer install` and both `composer require mckenziearts/laravel-notify` and `composer require mckenziearts/laravel-notify 1.*` but no success

**Comment by Mansjoer** [comment]
Yes, I get that error too. I think we should wait until the dev update it to a new version

**Comment by martijnschuman** [comment]
> Yes, I get that error too. I think we should wait until the dev update it to a new version

Yeah I think so, but the weird thing is that if you look at the [Pull Requests](https://github.com/mckenziearts/laravel-notify/pull) you can see a pull request from 22 days ago that should have added Laravel 9 support

**Comment by Mansjoer** [comment]
Yeah I didnt even know if the developer is still active or not

**Comment by gregmsanderson** [comment]
Yep, getting the same error
