### ISSUE TITLE
 line 98 of readme.md maybe @include('notify::components.notify')

### ISSUE THREAD

**Issue by supgeek-rod** [mckenziearts/laravel-notify#98]
https://github.com/mckenziearts/laravel-notify/blob/a75449fcc1a3e50ac8d1d41a026142461017b4ca/readme.md?plain=1#L98

I refer to  `line 98 of readme.md` write it in the layout view file `@include('notify::messages')`, then I got the following error

```
InvalidArgumentException
View [messages] not found. (View: /mnt/s/WorkSpaces/HeyCommunity/HeyCommunity-backend/resources/views/dashboard/layouts/default.blade.php)
```

Meybe line 98 should be the same as line 65?

https://github.com/mckenziearts/laravel-notify/blob/a75449fcc1a3e50ac8d1d41a026142461017b4ca/readme.md?plain=1#L65

**Comment by mckenziearts** [comment]
Fix on new release
